language: ruby
cache: bundler
dist: trusty
addons:
  chrome: stable
before_install:
  - bin/chromedriver-install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bin/rspec
